### ISSUE TITLE
Please fix the demo issue for new browsers

### ISSUE THREAD

**Issue by RCRawat** [Q42/fabricjs-opentypejs-demo#3]
Demo not working
please create easy documentation

**Comment by lukasvan3l** [comment]
Thanks for bringing this to my attention. Apparently browsers now send font size in decimals, like `25.8674px AutumnA1`. The code now supports this, and the demo "works on my machine" ;)

https://github.com/Q42/fabricjs-opentypejs-demo/commit/585e44eba1918b493b7397e312687d4c406e2fd7
